// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: rockim/shared/reasons/reasons.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace RockIM.Shared.Reasons {

  /// <summary>Holder for reflection information generated from rockim/shared/reasons/reasons.proto</summary>
  public static partial class ReasonsReflection {

    #region Descriptor
    /// <summary>File descriptor for rockim/shared/reasons/reasons.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ReasonsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiNyb2NraW0vc2hhcmVkL3JlYXNvbnMvcmVhc29ucy5wcm90bxIVcm9ja2lt",
            "LnNoYXJlZC5yZWFzb25zKh8KC0Vycm9yUmVhc29uEhAKDFVOX1NQRUNJRklF",
            "RBAAQl0KGGNuLnJvY2tpbS5zaGFyZWQucmVhc29uc1ABWidyb2NraW1zZXJ2",
            "ZXIvYXBpcy9yb2NraW0vc2hhcmVkL3JlYXNvbnOqAhVSb2NrSU0uU2hhcmVk",
            "LlJlYXNvbnNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::RockIM.Shared.Reasons.ErrorReason), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// ErrorReason 基础错误原因
  /// </summary>
  public enum ErrorReason {
    /// <summary>
    /// 未知错误
    /// </summary>
    [pbr::OriginalName("UN_SPECIFIED")] UnSpecified = 0,
  }

  #endregion

}

#endregion Designer generated code
