// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: rockim/api/client/v1/protocol/http/message.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace RockIM.Api.Client.V1.Protocol.Http {

  /// <summary>Holder for reflection information generated from rockim/api/client/v1/protocol/http/message.proto</summary>
  public static partial class MessageReflection {

    #region Descriptor
    /// <summary>File descriptor for rockim/api/client/v1/protocol/http/message.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjByb2NraW0vYXBpL2NsaWVudC92MS9wcm90b2NvbC9odHRwL21lc3NhZ2Uu",
            "cHJvdG8SInJvY2tpbS5hcGkuY2xpZW50LnYxLnByb3RvY29sLmh0dHAaLXJv",
            "Y2tpbS9hcGkvY2xpZW50L3YxL3Byb3RvY29sL2h0dHAvaHR0cC5wcm90bxoo",
            "cm9ja2ltL2FwaS9jbGllbnQvdjEvdHlwZXMvbWVzc2FnZS5wcm90bxohcm9j",
            "a2ltL3NoYXJlZC9lbnVtcy9tZXNzYWdlLnByb3RvIvYCChJNZXNzYWdlU2Vu",
            "ZFJlcXVlc3QSPAoEYmFzZRgBIAEoCzIuLnJvY2tpbS5hcGkuY2xpZW50LnYx",
            "LnByb3RvY29sLmh0dHAuQVBJUmVxdWVzdBI0CgZ0YXJnZXQYAiABKAsyJC5y",
            "b2NraW0uYXBpLmNsaWVudC52MS50eXBlcy5UYXJnZXRJRBIVCg1jbGllbnRf",
            "bXNnX2lkGAMgASgJEj4KDG1lc3NhZ2VfdHlwZRgEIAEoDjIoLnJvY2tpbS5z",
            "aGFyZWQuZW51bXMuTWVzc2FnZS5NZXNzYWdlVHlwZRIPCgdjb250ZW50GAUg",
            "ASgMElQKB3BheWxvYWQYBiADKAsyQy5yb2NraW0uYXBpLmNsaWVudC52MS5w",
            "cm90b2NvbC5odHRwLk1lc3NhZ2VTZW5kUmVxdWVzdC5QYXlsb2FkRW50cnka",
            "LgoMUGF5bG9hZEVudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToC",
            "OAEiFQoTTWVzc2FnZVNlbmRSZXNwb25zZTKHAQoKTWVzc2FnZUFQSRJ5CgRT",
            "ZW5kEjYucm9ja2ltLmFwaS5jbGllbnQudjEucHJvdG9jb2wuaHR0cC5NZXNz",
            "YWdlU2VuZFJlcXVlc3QaNy5yb2NraW0uYXBpLmNsaWVudC52MS5wcm90b2Nv",
            "bC5odHRwLk1lc3NhZ2VTZW5kUmVzcG9uc2UiAEJgWjlyb2NraW1zZXJ2ZXIv",
            "YXBpcy9yb2NraW0vYXBpL2NsaWVudC92MS9wcm90b2NvbC9odHRwO2h0dHCq",
            "AiJSb2NrSU0uQXBpLkNsaWVudC5WMS5Qcm90b2NvbC5IdHRwYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::RockIM.Api.Client.V1.Protocol.Http.HttpReflection.Descriptor, global::RockIM.Api.Client.V1.Types.MessageReflection.Descriptor, global::RockIM.Shared.Enums.MessageReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::RockIM.Api.Client.V1.Protocol.Http.MessageSendRequest), global::RockIM.Api.Client.V1.Protocol.Http.MessageSendRequest.Parser, new[]{ "Base", "Target", "ClientMsgId", "MessageType", "Content", "Payload" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::RockIM.Api.Client.V1.Protocol.Http.MessageSendResponse), global::RockIM.Api.Client.V1.Protocol.Http.MessageSendResponse.Parser, null, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// MessageSendRequest 发送消息请求
  /// </summary>
  public sealed partial class MessageSendRequest : pb::IMessage<MessageSendRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MessageSendRequest> _parser = new pb::MessageParser<MessageSendRequest>(() => new MessageSendRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MessageSendRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::RockIM.Api.Client.V1.Protocol.Http.MessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MessageSendRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MessageSendRequest(MessageSendRequest other) : this() {
      base_ = other.base_ != null ? other.base_.Clone() : null;
      target_ = other.target_ != null ? other.target_.Clone() : null;
      clientMsgId_ = other.clientMsgId_;
      messageType_ = other.messageType_;
      content_ = other.content_;
      payload_ = other.payload_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MessageSendRequest Clone() {
      return new MessageSendRequest(this);
    }

    /// <summary>Field number for the "base" field.</summary>
    public const int BaseFieldNumber = 1;
    private global::RockIM.Api.Client.V1.Protocol.Http.APIRequest base_;
    /// <summary>
    /// 基本参数
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::RockIM.Api.Client.V1.Protocol.Http.APIRequest Base {
      get { return base_; }
      set {
        base_ = value;
      }
    }

    /// <summary>Field number for the "target" field.</summary>
    public const int TargetFieldNumber = 2;
    private global::RockIM.Api.Client.V1.Types.TargetID target_;
    /// <summary>
    /// 发送的目标
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::RockIM.Api.Client.V1.Types.TargetID Target {
      get { return target_; }
      set {
        target_ = value;
      }
    }

    /// <summary>Field number for the "client_msg_id" field.</summary>
    public const int ClientMsgIdFieldNumber = 3;
    private string clientMsgId_ = "";
    /// <summary>
    /// 客户端的消息ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ClientMsgId {
      get { return clientMsgId_; }
      set {
        clientMsgId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "message_type" field.</summary>
    public const int MessageTypeFieldNumber = 4;
    private global::RockIM.Shared.Enums.Message.Types.MessageType messageType_ = global::RockIM.Shared.Enums.Message.Types.MessageType.Text;
    /// <summary>
    /// 消息类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::RockIM.Shared.Enums.Message.Types.MessageType MessageType {
      get { return messageType_; }
      set {
        messageType_ = value;
      }
    }

    /// <summary>Field number for the "content" field.</summary>
    public const int ContentFieldNumber = 5;
    private pb::ByteString content_ = pb::ByteString.Empty;
    /// <summary>
    /// 消息内容
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Content {
      get { return content_; }
      set {
        content_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "payload" field.</summary>
    public const int PayloadFieldNumber = 6;
    private static readonly pbc::MapField<string, string>.Codec _map_payload_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForString(18, ""), 50);
    private readonly pbc::MapField<string, string> payload_ = new pbc::MapField<string, string>();
    /// <summary>
    /// 透传数据
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, string> Payload {
      get { return payload_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MessageSendRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MessageSendRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Base, other.Base)) return false;
      if (!object.Equals(Target, other.Target)) return false;
      if (ClientMsgId != other.ClientMsgId) return false;
      if (MessageType != other.MessageType) return false;
      if (Content != other.Content) return false;
      if (!Payload.Equals(other.Payload)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (base_ != null) hash ^= Base.GetHashCode();
      if (target_ != null) hash ^= Target.GetHashCode();
      if (ClientMsgId.Length != 0) hash ^= ClientMsgId.GetHashCode();
      if (MessageType != global::RockIM.Shared.Enums.Message.Types.MessageType.Text) hash ^= MessageType.GetHashCode();
      if (Content.Length != 0) hash ^= Content.GetHashCode();
      hash ^= Payload.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (base_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Base);
      }
      if (target_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Target);
      }
      if (ClientMsgId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ClientMsgId);
      }
      if (MessageType != global::RockIM.Shared.Enums.Message.Types.MessageType.Text) {
        output.WriteRawTag(32);
        output.WriteEnum((int) MessageType);
      }
      if (Content.Length != 0) {
        output.WriteRawTag(42);
        output.WriteBytes(Content);
      }
      payload_.WriteTo(output, _map_payload_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (base_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Base);
      }
      if (target_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Target);
      }
      if (ClientMsgId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ClientMsgId);
      }
      if (MessageType != global::RockIM.Shared.Enums.Message.Types.MessageType.Text) {
        output.WriteRawTag(32);
        output.WriteEnum((int) MessageType);
      }
      if (Content.Length != 0) {
        output.WriteRawTag(42);
        output.WriteBytes(Content);
      }
      payload_.WriteTo(ref output, _map_payload_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (base_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Base);
      }
      if (target_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Target);
      }
      if (ClientMsgId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ClientMsgId);
      }
      if (MessageType != global::RockIM.Shared.Enums.Message.Types.MessageType.Text) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) MessageType);
      }
      if (Content.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Content);
      }
      size += payload_.CalculateSize(_map_payload_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MessageSendRequest other) {
      if (other == null) {
        return;
      }
      if (other.base_ != null) {
        if (base_ == null) {
          Base = new global::RockIM.Api.Client.V1.Protocol.Http.APIRequest();
        }
        Base.MergeFrom(other.Base);
      }
      if (other.target_ != null) {
        if (target_ == null) {
          Target = new global::RockIM.Api.Client.V1.Types.TargetID();
        }
        Target.MergeFrom(other.Target);
      }
      if (other.ClientMsgId.Length != 0) {
        ClientMsgId = other.ClientMsgId;
      }
      if (other.MessageType != global::RockIM.Shared.Enums.Message.Types.MessageType.Text) {
        MessageType = other.MessageType;
      }
      if (other.Content.Length != 0) {
        Content = other.Content;
      }
      payload_.Add(other.payload_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (base_ == null) {
              Base = new global::RockIM.Api.Client.V1.Protocol.Http.APIRequest();
            }
            input.ReadMessage(Base);
            break;
          }
          case 18: {
            if (target_ == null) {
              Target = new global::RockIM.Api.Client.V1.Types.TargetID();
            }
            input.ReadMessage(Target);
            break;
          }
          case 26: {
            ClientMsgId = input.ReadString();
            break;
          }
          case 32: {
            MessageType = (global::RockIM.Shared.Enums.Message.Types.MessageType) input.ReadEnum();
            break;
          }
          case 42: {
            Content = input.ReadBytes();
            break;
          }
          case 50: {
            payload_.AddEntriesFrom(input, _map_payload_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (base_ == null) {
              Base = new global::RockIM.Api.Client.V1.Protocol.Http.APIRequest();
            }
            input.ReadMessage(Base);
            break;
          }
          case 18: {
            if (target_ == null) {
              Target = new global::RockIM.Api.Client.V1.Types.TargetID();
            }
            input.ReadMessage(Target);
            break;
          }
          case 26: {
            ClientMsgId = input.ReadString();
            break;
          }
          case 32: {
            MessageType = (global::RockIM.Shared.Enums.Message.Types.MessageType) input.ReadEnum();
            break;
          }
          case 42: {
            Content = input.ReadBytes();
            break;
          }
          case 50: {
            payload_.AddEntriesFrom(ref input, _map_payload_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// MessageSendResponse 发送消息响应
  /// </summary>
  public sealed partial class MessageSendResponse : pb::IMessage<MessageSendResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MessageSendResponse> _parser = new pb::MessageParser<MessageSendResponse>(() => new MessageSendResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MessageSendResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::RockIM.Api.Client.V1.Protocol.Http.MessageReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MessageSendResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MessageSendResponse(MessageSendResponse other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MessageSendResponse Clone() {
      return new MessageSendResponse(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MessageSendResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MessageSendResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MessageSendResponse other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
